on:
  push:
    branches:
      - master
      - beta
name: Release
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build:schema
      - run: cp payload-examples/index.{d.ts,json} ./
      - run: cp payload-schemas/schema.json ./schema.json
      - run: cp payload-types/schema.d.ts ./schema.d.ts
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT }}
          NPM_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
      - run: npm publish payload-examples | exit 0
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
        if: ${{ github.ref == 'refs/heads/master' }}
      - run: npm publish payload-examples --tag beta | exit 0
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
        if: ${{ github.ref == 'refs/heads/beta' }}
      - run: npm publish payload-schemas | exit 0
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
        if: ${{ github.ref == 'refs/heads/master' }}
      - run: npm publish payload-schemas --tag beta | exit 0
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
        if: ${{ github.ref == 'refs/heads/beta' }}
      - run: npm publish payload-types | exit 0
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
        if: ${{ github.ref == 'refs/heads/master' }}
      - run: npm publish payload-types --tag beta | exit 0
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
        if: ${{ github.ref == 'refs/heads/beta' }}
